---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.controller.demo
  resources:
  - podcontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.controller.demo
  resources:
  - podcontrollers/finalizers
  verbs:
  - update
- apiGroups:
  - apps.controller.demo
  resources:
  - podcontrollers/status
  verbs:
  - get
  - patch
  - update
