apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.demo.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.demo.replicaCount }} 
  selector:
    matchLabels:
      app: {{ .Values.demo.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.demo.name }}        
    spec:
      containers:
      - image: {{ .Values.demo.image }}
        imagePullPolicy: {{ .Values.demo.pullPolicy }}
        name: {{ .Values.demo.name }}
        ports:
          - name: demoport
            containerPort: {{ .Values.demo.apiport }}
            protocol: TCP
        livenessProbe:
          tcpSocket:
            port: demoport
          initialDelaySeconds: 15
          failureThreshold: 3
          periodSeconds: 10
      