apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.demo.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.demo.name }}
  type: NodePort  
  ports:
    - name: apiport
      protocol: TCP
      nodePort: 30036
      port: 80
      targetPort: {{ .Values.demo.apiport }}
